name: docker

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
        if: ${{ env.ACT != 'true' }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        if: ${{ env.ACT != 'true' && env.PUSH_IMAGE != 'false' }}
        with:
          registry: ${{ env.DOCKERHUB_REGISTRY || 'docker.io' }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v5
        if: ${{ env.ACT != 'true' }}
        with:
          images: wavesman/pinktide
          tags: |
            type=ref,event=tag
            type=raw,value=latest

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ env.ACT != 'true' && env.PUSH_IMAGE != 'false' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags || 'wavesman/pinktide:local' }}
          labels: ${{ steps.meta.outputs.labels || '' }}
          build-args: |
            DOCKER_REGISTRY=${{ secrets.DOCKER_REGISTRY || env.DOCKER_REGISTRY || 'docker.io/library/' }}
            GOPROXY=${{ secrets.GOPROXY || env.GOPROXY || '' }}
            VERSION=${{ github.ref_name || 'dev' }}
